config/routes.rb
Rails.application.routes.draw do


  # custom path/controller for importing
  post '/upload', to: 'affiliation_importer#upload', as: 'process_import'

  resources :affiliations

  # authentication of login - logout
  devise_for :users

  # Defines the root path route ("/")
  root "affiliations#index"
end

app/models/affiliation.rb
class Affiliation < ApplicationRecord


# ======[ properties rules ]========




# ======[	relationships rules ]========
	has_and_belongs_to_many :people, -> { distinct }



# ======[	validation rules ]========
	validates :name, presence: true, uniqueness: { case_sensitive: false }
	
	validate :name_is_titlecased
	def name_is_titlecased
		if name.present? && !name.start_with?(/[A-Z]/)
			errors.add(:name, "should be titlecased")
		end
	end


# ======[ Hooks ]========

# ======[ other methods ]========

end

app/models/application_record.rb
# :nocov:
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end
# :nocov:

app/models/location.rb
class Location < ApplicationRecord

# ======[ properties rules ]========




# ======[	relationships rules ]========
	has_and_belongs_to_many :people,  -> { distinct }



# ======[	validation rules ]========
	validates :address, presence: true, uniqueness: { case_sensitive: false }
	


	validate :name_is_titlecased
	def name_is_titlecased
		if address.present? && !address.start_with?(/[A-Z]/)
			errors.add(:address, "should be titlecased")
		end
	end

# ======[ Hooks ]========
	before_save :sanitize_data

	def sanitize_data
		self.address = self.address.titlecase	if self.address.present?
		# 
		return true
	end


# ======[ other methods ]========

end

app/models/person.rb
class Person < ApplicationRecord

# ======[ properties rules ]========
  
  enum gender: [ :male, :female, :unspecified ]

# ======[ relationships rules ]========

  # A Person can belong to many Locations
  has_and_belongs_to_many :locations,  -> { distinct }
 
  # A Person can belong to many Affiliations
  has_and_belongs_to_many :affiliations,   -> { distinct }

# ======[ validation rules ]========

  # Person should have both a first_name and last_name. 
  validates :first_name, presence: true

  # this rule was commented out because C3-PO and R2-D2 was being ignored
  # 
  # validates_format_of :first_name, :with => /^([^\d\W]|[-])*$/, :multiline => true, :message => "should be string"


  validate :first_name_is_titlecased
  def first_name_is_titlecased
    unless first_name.present? && first_name.start_with?(/[A-Z]/)
      errors.add(:first_name, "should be titlecased")
    end
  end

  validate :last_name_is_titlecased
  def last_name_is_titlecased
    if last_name.present? && !last_name.start_with?(/[A-Z]/)
      errors.add(:last_name, "should be titlecased")
    end
  end



# ======[ Hooks ]========



# ======[ other methods ]========



  def self.gender_parser str
    str = str.downcase.strip

    if ["m", "male"].include?(str)
      res = :male
    elsif ["f", "female"].include?(str)
      res = :female
    else
      res = :unspecified
    end

    res
  end

  # takes any name piece joins them up
  # (except first part)
  def self.get_last_names names
    names[1, names.length].join(" ")
  end

  # function to sanitize the name string
  # takes a string, splits by space
  #
  def self.name_sanitizer res

    # tried adding exception in the inflection, but didn't work
    res.humanize.gsub(/\b('?[a-z])/) { $1.capitalize }.split(' ')
  end

  def name
    "#{first_name} #{last_name}"
  end

  def name=(str)
    names = Person.name_sanitizer( str )
    self.first_name = names[0]
    self.last_name = Person.get_last_names( names )
  end
end

app/models/user.rb
# :nocov:
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end
# :nocov:

app/controllers/affiliation_importer_controller.rb
require 'csv'
class AffiliationImporterController < ApplicationController
  
  before_action :authenticate_user!
  before_action :check_if_file_present
  

  # POST /upload 
  def upload

    deadgum = nil

    csv_file =  File.read(params[:import_csv_file].tempfile)
    table = CSV.parse(csv_file.gsub(/\r\n?/,"\n"), headers: true, :row_sep => :auto, :col_sep => ",")

    if table.length < 1 or !table.headers.include? "Affiliations"
      deadgum = "File has no valid content."
    else

      ImporterService.call(table)
    end

    respond_to do |format|
      if deadgum.blank?
        format.html { redirect_to affiliations_url, notice: 'Database was successfully updated.' }
      else
        format.html { redirect_to affiliations_url, alert: deadgum }
      end
    end

  end

  private

    # performs some housekeeping around the file upload
    #
    def check_if_file_present

      unless params[:import_csv_file].present?
        redirect_to affiliations_url, flash: { alert: "File missing" } and return
      end

      if params[:import_csv_file].content_type != "text/csv"
        # not really a full proof check
        redirect_to affiliations_url, flash: { alert: "File is not a CSV" } and return
      end

      begin

        csv_file =  File.read(params[:import_csv_file].tempfile)

      rescue Errno::ENOENT => e
        
        deadgum = "File or directory #{params[:import_csv_file]} doesn't exist."
        redirect_to affiliations_url, flash: { alert: deadgum } and return
      
      rescue Errno::EACCES => e
        
        deadgum = "Can't read from #{params[:import_csv_file]}. No permission."
        redirect_to affiliations_url, flash: { alert: deadgum } and return
      end


    end
end

app/controllers/affiliations_controller.rb
class AffiliationsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_affiliation, only: %i[ show edit update destroy ]

  # GET /affiliations or /affiliations.json
  def index
    @affiliations = Affiliation.all
  end

  # GET /affiliations/1 or /affiliations/1.json
  def show
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_affiliation
      @affiliation = Affiliation.find(params[:id])
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/affiliations_helper.rb
module AffiliationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/affiliations/_affiliation.html.erb
<div id="<%= dom_id affiliation %>">
  

<div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-2 xl:grid-cols-2 gap-5">
<% @affiliation.people.each do |people| %>

<div class="flex flex-col items-center bg-white rounded-lg border shadow-md md:flex-row md:max-w-xl hover:bg-gray-100 dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700">
    
    <div class="object-cover w-full h-56 rounded-t-lg md:h-auto md:w-86 md:rounded-none md:rounded-l-lg">
      <%= render "partials/stormy" %>
    </div>

    <div class="flex flex-col justify-between p-4 leading-normal">
        <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">
          <%= people.name %>
        </h5>
        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">
          <%= people.locations.map(&:address).join(",") %>
        </p>
        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">
          <b>Gender:</b> <%= people.gender %> <br>
          <b>Species:</b> <%= people.species %> <br>
          <b>Weapon:</b> <%= people.weapon %> <br>
          <b>Vehicle:</b> <%= people.vehicle %> <br>
        </p>
    </div>
</div>
<% end %>

</div>
</div>

app/views/affiliations/_csv_importer.html.erb
<div class="p-4 my-8 bg-white rounded-lg border border-gray-200 shadow-md sm:p-6 lg:p-8 dark:bg-gray-800 dark:border-gray-700">
<h3 class="mb-3 text-xl font-medium text-gray-900 dark:text-white">Database Access</h3>

<p class="mb-5 text-sm font-medium text-gray-500 dark:text-gray-300">Do you want to contribute your source of information to the central database? Upload your latest source of data!</p>

<%= form_tag( process_import_path, { :multipart => true, :class => "group relative"} ) do %>

    <div class="flex items-baseline mb-3">
    <div class="relative mr-2 w-full revue-form-group">

    <%= file_field_tag :import_csv_file, 
            class: "block w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 cursor-pointer dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400", 
            :accept => 'text/csv', 
            :required => true %>

    <p class="mt-1 text-sm text-gray-500 dark:text-gray-300" id="file_input_help">Accepts only *.csv.</p>

    </div>
    <div class="revue-form-actions">
      <%= submit_tag :Upload, class: "cursor-pointer text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
    </div>
    </div>

<% end %>
</div>

app/views/affiliations/index.html.erb
<%= render "csv_importer" %>

<section>
  <header class="bg-white space-y-4 p-4 sm:px-8 sm:py-6 lg:p-4 xl:px-8 xl:py-6">
    <div class="flex items-center justify-between">
      <h2 class="mb-3 text-xl font-medium text-gray-900 dark:text-white">Affiliations</h2>
    </div>
    
  </header>


  <div class="overflow-x-auto relative bg-white space-y-4 p-4 sm:px-8 sm:py-6 lg:p-4 xl:px-8 xl:py-6">

    <%
      # create a header row
      colnames = ["#", "Name", "Location", "Species", "Gender" , "Affiliations", "Weapon", "Vehicle" ]
      # Iterate over the strings with "each."
      header = "<tr>"
      colnames.each do |st|
        header += "<th class='px-6 py-2 text-xs text-gray-500'>#{st}</th>"
      end
      header += "</tr>"
    %>


    <% if @affiliations.count < 1 %>
      <p class="mb-5 text-sm font-medium text-gray-500 dark:text-gray-300">Seems like we have no new data in this category, how about you create something?</p>
    <% else %>

      <table class="divide-y divide-gray-300 pt-5 pb-5" data-page-length='10' id="dataTable">
          <thead class="bg-gray-100">
            <%= header.html_safe %>
          </thead>
          <tbody class="bg-white divide-y divide-gray-500">
            <% @affiliations.map(&:people).flatten.uniq.each do |people| %>

              <tr class="whitespace-nowrap">
                <td class="px-6 py-4 text-sm text-center text-gray-500">
                    <%= people.id %>
                </td>
                <td class="px-6 py-4 text-sm text-left text-gray-500">
                    <%= people.name %>
                </td>
                <td class="px-6 py-4 text-sm text-left text-gray-500">
                    <% people.locations.each do |loc|  %>
                    <%= "##{loc.id} #{loc.address}" %>
                    <% end %>
                </td>
                <td class="px-6 py-4 text-sm text-left text-gray-500">
                    <%= people.species %>
                </td>
                <td class="px-6 py-4 text-sm text-left text-gray-500">
                    <%= people.gender.upcase %>
                </td>
                <td class="px-6 py-4 text-sm">
                    <% people.affiliations.each do |affiliation| %>
                         <%= link_to affiliation.name, affiliation_path(affiliation), class: "underline text-blue-600 hover:text-blue-800 visited:text-purple-600" %>
                    <% end %>
                </td>
                <td class="px-6 py-4 text-sm text-left text-gray-500">
                    <%= people.weapon %>
                </td>
                <td class="px-6 py-4 text-sm text-left text-gray-500">
                    <%= people.vehicle %>
                </td>
              </tr>
            <% end %>
          </tbody>
      </table>


    <% end %>


</div>
</section>

app/views/affiliations/show.html.erb
 

  <div class="overflow-x-auto relative bg-white space-y-4 p-4 sm:px-8 sm:py-6 lg:p-4 xl:px-8 xl:py-6">



<% unless current_page?(root_path) %>
  
  <span class="text-base text-purple-500 font-bold">&laquo;</span> 
  <a href="#" onClick="history.back()" class="text-base md:text-sm text-purple-500 font-bold no-underline hover:underline">Back Link</a>

<% end %>

        
<!--Title-->
<div class="font-sans">
   <h1 class="font-sans break-normal text-gray-900 pt-6 pb-2 text-xl"><%= @affiliation.name %></h1>
   <hr class="border-b border-gray-400">
</div>
<!--Post Content-->

<% if user_signed_in? %>
    <%= render @affiliation %>
<% else %>
  <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice">You need to Login to see the magic.</p>
<% end %>

<!--/ Post Content-->



</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>New Hope</title>
    <meta name="author" content="Nishat">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-100 tracking-wider tracking-normal">

      <!-- navbar for signin signout -->
      <nav id="header" class="fixed w-full z-10 top-0 bg-white border-b border-gray-400">
         <div class="w-full container mx-auto flex flex-wrap items-center justify-between mt-0 py-4">
            <div class="pl-4 flex items-center">
               
               <%= link_to root_path, class: "text-gray-900 text-base no-underline hover:no-underline font-extrabold text-xl" do %>
                    <div style="width:50px">
                       <!-- stormy -->
                       <%= render "partials/stormy" %>
                    </div>
                   
                   A NEW HOPE
               <% end %>
            </div>
            

               <ul class="list-reset lg:flex justify-end items-center">
                  
                  <% if user_signed_in? %>
                     <li class="mr-3 py-2 lg:py-0">
                        Hi <%= current_user.email %>!
                     </li>
                     <li class="mr-3 py-2 lg:py-0">
                        <%= button_to "Log out", destroy_user_session_path, method: :delete %>
                     </li>

                  <% else %>

                     <li class="mr-3 py-2 lg:py-0">
                        <%= link_to "Log in", new_user_session_path, class: "inline-block text-gray-600 no-underline hover:text-gray-900 hover:underline py-2 px-4" %>
                     </li>

                  <% end %>


               </ul>
            
         </div>
      </nav>


      <main class="container w-full flex flex-wrap mx-auto px-2 pt-8 lg:pt-16 mt-16">

        <div class="w-full notice-container">
          <% if defined?(notice) && notice != nil %>
            <div class="bg-green-500">
              <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans"><%= notice %></div>
            </div>
          <% end %>

          <% if defined?(alert) && alert != nil  %>
            <div class="bg-red-500">
              <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans"><%= alert %></div>
            </div>
          <% end %>
        </div>

        <div class="w-full notice-container pt-8">
          <%= yield %>
        </div>
      </main>



  </body>


</html>

app/views/people/_form.html.erb
<%= form_with(model: person, class: "contents") do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :gender %>
    <%= form.number_field :gender, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :weapon %>
    <%= form.text_field :weapon, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :vehicle %>
    <%= form.text_field :vehicle, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/people/_person.html.erb
<div id="<%= dom_id person %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">First name:</strong>
    <%= person.first_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Last name:</strong>
    <%= person.last_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Gender:</strong>
    <%= person.gender %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Weapon:</strong>
    <%= person.weapon %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Vehicle:</strong>
    <%= person.vehicle %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this person", person, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this person', edit_person_path(person), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/people/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing person</h1>

  <%= render "form", person: @person %>

  <%= link_to "Show this person", @person, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to people", people_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/people/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">People</h1>
    <%= link_to 'New person', new_person_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="people" class="min-w-full">
    <%= render @people %>
  </div>
</div>

app/views/people/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New person</h1>

  <%= render "form", person: @person %>

  <%= link_to 'Back to people', people_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/people/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @person %>

    <%= link_to 'Edit this person', edit_person_path(@person), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this person', person_path(@person), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to people', people_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>